name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to EC2
        run: |
          aws s3 cp your-artifact.jar s3://your-bucket-name/your-artifact.jar
          aws ec2 run-instances --image-id ami-your-ami-id --count 1 --instance-type t2.micro --key-name your-key-pair --security-group-ids your-security-group --subnet-id your-subnet-id --user-data file://path/to/your/user-data-script.sh
