name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ] # Replace "build" with the name of the job that builds and pushes the Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          echo "Host ec2-instance\n\
            HostName <EC2_PUBLIC_IP_ADDRESS>\n\
            User ec2-user\n\
            IdentityFile private_key" > ssh_config

      - name: Deploy to EC2 instance
        run: |
          scp -F ssh_config -r docker-compose.yml ec2-instance:/home/ec2-user/babalance
          ssh -F ssh_config ec2-instance "\
            cd babalance && \
            docker-compose pull && \
            docker-compose up -d"